name: Go
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    - 'test*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        bash scripts/ci_release.sh windows amd64
        bash scripts/ci_release.sh windows 386
        bash scripts/ci_release.sh linux amd64
        bash scripts/ci_release.sh linux 386
        bash scripts/ci_release.sh linux arm64
        bash scripts/ci_release.sh linux arm
        bash scripts/ci_release.sh linux mipsle
        bash scripts/ci_release.sh linux mips
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          cloud-torrent_windows_amd64.exe.gz
          cloud-torrent_windows_386.exe.gz
          cloud-torrent_linux_amd64.gz
          cloud-torrent_linux_386.gz
          cloud-torrent_linux_arm64.gz
          cloud-torrent_linux_arm.gz
          cloud-torrent_linux_mipsle.gz
          cloud-torrent_linux_mips.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

